@api
Feature: Ensures all basic configuration of the Drupal site remains in place.

  Scenario: Warm up browser early in tests.
    Given I am at "/user"

  @javascript
  Scenario: Warm up javscript browser early in tests.
    Given I am at "/user"

  Scenario Outline: Critical modules are enabled on the site.
    Given The module "<module>" should be enabled

    Examples:
      | module                  |
      | action |
      | address |
      | admin_toolbar |
      | admin_toolbar_tools |
      | atdove_admin |
      | atdove_billing |
      | atdove_default_content |
      | atdove_migrate |
      | atdove_opigno |
      | atdove_organizations |
      | atdove_organizations_create |
      | atdove_organizations_invite |
      | atdove_sso |
      | atdove_users |
      | atdove_utilities |
      | automated_cron |
      | better_exposed_filters |
      | block |
      | block_content |
      | breakpoint |
      | bulk_user_registration |
      | calendar |
      | calendar_datetime |
      | ckeditor |
      | ckeditor_bgimage |
      | ckeditor_font |
      | color |
      | comment |
      | config |
      | config_filter |
      | config_rewrite |
#      | config_split |
      | contact |
      | contextual |
      | core_event_dispatcher |
      | csv_serialization |
      | ctools |
      | datetime |
      | datetime_range |
      | dblog |
      | dropzonejs |
      | dropzonejs_eb_widget |
      | dynamic_page_cache |
      | editor |
      | embed |
      | entity |
      | entity_browser |
      | entity_browser_entity_form |
      | entity_embed |
      | entity_print |
      | entity_print_views |
      | entity_reference_revisions |
      | feeds |
      | field |
      | field_group |
      | field_group_migrate |
      | field_ui |
      | file |
      | file_delete |
      | filter |
      | flag |
      | flag_bookmark |
      | flag_count |
      | flag_lists |
      | flag_lists_actions |
      | ggroup |
      | ginvite |
      | gnode |
      | group |
      | h5p |
      | h5peditor |
      | heading |
      | help |
      | history |
      | hook_event_dispatcher |
      | image |
      | inline_entity_form |
      | jquery_ui |
      | jquery_ui_datepicker |
      | jquery_ui_slider |
      | jquery_ui_touch_punch |
      | key |
      | language |
      | layout_builder |
      | layout_discovery |
      | link |
      | mailsystem |
      | masquerade |
      | media |
      | media_entity_browser |
      | media_entity_browser_media_library |
      | media_library |
      | menu_link_content |
      | menu_ui |
      | message |
      | message_notify |
      | migrate |
      | migrate_drupal |
      | migrate_drupal_ui |
      | migrate_file |
      | migrate_file_to_media |
      | migrate_plus |
      | migrate_tools |
      | migrate_upgrade |
      | mimemail |
      | multiselect |
      | node |
      | node_view_permissions |
      | openid_connect |
      | opigno_alter_entity_autocomplete |
      | opigno_calendar |
      | opigno_calendar_event |
      | opigno_calendar_event_group |
      | opigno_catalog |
      | opigno_certificate |
      | opigno_class |
      | opigno_course |
      | opigno_cron |
      | opigno_dashboard |
      | opigno_file_upload |
      | opigno_forum |
      | opigno_group_manager |
      | opigno_h5p |
      | opigno_ilt |
      | opigno_learning_path |
      | opigno_like |
      | opigno_long_answer |
      | opigno_messaging |
      | opigno_migration |
      | opigno_module |
      | opigno_module_group |
      | opigno_moxtra |
      | opigno_notification |
      | opigno_scorm |
      | opigno_scorm_activity |
      | opigno_search |
      | opigno_skills_system |
      | opigno_social |
      | opigno_statistics |
      | opigno_tincan_activities |
      | opigno_tincan_activity |
      | opigno_tincan_api |
      | opigno_tincan_badges |
      | opigno_tincan_courses |
      | opigno_tincan_ilt |
      | opigno_tincan_learning_path |
      | opigno_tincan_live_meeting |
      | opigno_tincan_modules |
      | opigno_user_selection |
      | opigno_video |
      | options |
      | page_cache |
      | path |
      | path_alias |
      | pdf |
      | popup_field_group |
      | private_message |
      | queue_ui |
      | quickedit |
      | rdf |
      | redirect |
      | rest |
      | role_delegation |
      | search_api |
      | search_api_db |
      | search_api_exclude_entity |
      | serialization |
      | shortcut |
      | simple_gmap |
      | state_machine |
      | system |
      | taxonomy |
      | telephone |
      | text |
      | tft |
      | token |
      | token_filter |
      | toolbar |
      | twig_field_value |
      | twig_tweak |
      | ultimate_cron |
      | update |
      | user |
      | userprotect |
      | variationcache |
      | video |
      | video_embed_field |
      | video_embed_media |
      | views_bulk_operations |
      | views_data_export |
      | views_infinite_scroll |
      | views_templates |
      | webform |
      | webform_submission_export_import |
      | webform_submission_log |
      | webform_ui |
      | wistia |
      | forum |
      | pathauto |
      | comment_notify |
      | views          |
      | paragraphs     |
      | opigno_lms    |
