<?php

use Drupal\Core\Url;

/**
 * Implements hook_preprocess_page().
 */
function atdove_marketing_site_redirect_preprocess_page()
{
  // if authenticated, return
  if (\Drupal::currentUser()->isAuthenticated()) {
    return;
  }

  // if the requested page is an allowed anonymous url, then we'll let the request through.  Otherwise, redirect to go.atdove.org
  $requestPath = Url::fromRoute('<current>')->toString();

  $anonymousUrls = [
    '/join',
    '/user/login',
    '/user/password',
    '/user/reset',
    '/user/register',
    '/opigno-activity-search',
    '/webform/special-accounts',
    '/atdove-sso/openathens_bluepearl',
  ];
  foreach ($anonymousUrls as $url) {
    if (stripos($requestPath, $url) !== false) {
      return;
    }
  }

  header('Location: https://go.atdove.org');
  exit();
}
