<?php

/**
 * @file
 * Contains atdove_organizations_invite.module.
 */

// Include various hooks/functions organized by functionality.
\Drupal::moduleHandler()->loadInclude('atdove_organizations_invite', 'inc', 'includes/form/user_register');
\Drupal::moduleHandler()->loadInclude('atdove_organizations_invite', 'inc', 'includes/form/group_invite');

/**
 * Implements hook_entity_type_build().
 */
function atdove_organizations_invite_entity_type_build(array &$entity_types) {
  // Override access handler class for Group entity.
  if (isset($entity_types['group'])) {
    $entity_types['group']->setHandlerClass('access', 'Drupal\atdove_organizations_invite\Access\GroupAccessControlHandler');
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Preprocess menu-local-action.html.twig.
 */
function atdove_organizations_invite_preprocess_menu_local_action(&$vars) {
  // Clarify difference between invite member and invite members buttons.
  if ($vars["element"]["#link"]["title"] == 'Invite members') {
    $text = 'Invite multiple members';
    $vars["element"]["#link"]["title"] = $text;
    $vars["link"]["#title"] = $text;
  }
}
