#!/bin/bash

# Configures Drupal to establish database connection
# and any other settings needed to spin up the site.

set -eo pipefail

cp ./.ci/test/behat/env/.htaccess ./web/.htaccess
cp ./.ci/test/behat/env/settings.local.php ./web/sites/default/settings.local.php

# Create files directory in case there are tests that generate files.
mkdir -p ./web/sites/default/files
# Create h5p directory that some tests depend on. In theory
# we shouldn't have to create this ourselves if the files
# directory has the right permissions, but it can't hurt.
mkdir -p ./web/sites/default/files/h5p
mkdir -p ./web/sites/default/files/h5p/temp
# Because this directory will only exist temporarily,
# give it insecure permissions.
sudo chmod -R 777 ./web/sites/default/files
sudo chown -R www-data ./web/sites/default/files
