#!/bin/bash

# Installs Drupal and imports config for use in Behat tests
# when testing against a database with content is not desired.

set -eo pipefail

# A minimal profile Drupal created locally using the following command:
# - drush -y site:install minimal --site-name='Hello World' --site-mail=info@drupal-circleci-behat.localhost --account-name=admin --account-pass=admin
# - drush -y cex
# But you could also simply create a standard profile Drupal, set UUID to be the same as in system.site.yml and then import existing config:
# - drush -y site:install
# - drush -y ev '\Drupal::entityTypeManager()->getStorage("shortcut_set")->load("default")->delete();'
# - drush -y config-set "system.site" uuid "c6e1475a-d30b-4dac-9cba-7dc12de37090"
# - drush -y cim
./vendor/bin/drush -y site:install
./vendor/bin/drush -y ev '\Drupal::entityTypeManager()->getStorage("shortcut_set")->load("default")->delete();'
# @todo If copying this for new project, update next line based on value of uuid in system.site.yml.
./vendor/bin/drush -y config-set "system.site" uuid "7c82c2c4-3283-4d31-8bfb-836fee15f414"
echo "Importing all config..."
# See: https://stackoverflow.com/a/46921076/1401823
# We run config import for x mins until it completes to avoid memory limit.
while timeout 7m ./vendor/bin/drush config-import -y; [ $? -ne 0 ]
do
  :
done
echo "Config import complete"

echo "Running DB Updates"
./vendor/bin/drush updb -y;

echo "Clearing caches..."
./vendor/bin/drush cr;

# Get status for debugging purposes.
./vendor/bin/drush status;
