<?php

/**
 * @file
 * Contains atdove_contributor_bio.module.
 */


/**
 * Implements hook_theme().
 */
function atdove_contributor_bio_theme($existing, $type, $theme, $path) {

  return [
    // Name of the theme hook. This is used in the controller to trigger the hook.
    'atdove_contributor_bio__bio' => [
      'render element' => 'children',
      // If no template name is defined here, it defaults to the name of the theme hook, ie. module-name-theme-hook.html.twig
      'template' => 'contributor',
      // Optionally define path to Twig template files. Defaults to the module's ./templates/ directory.
      'path' => '/themes/custom/atdove/templates/user/profile',
      // Optionally define variables that will be passed to the Twig template and set default values for them.
      'variables' => [
        'contributorData' => []
      ],
    ],
  ];

}
