#!/bin/bash

set -eo pipefail

#
# This script runs static tests which
# can be performed without code execution.
#
# Some example are code sniffing and unit testing
#

# Commenting this out because we're running composer install in custom job.
# Run composer install to get the vendor directory
#composer install --no-ansi --no-interaction --optimize-autoloader --no-progress

# Run unit tests
composer -n unit-test

# Lint php code for syntax errors
composer -n lint

# Check coding standards
composer -n code-sniff
